#!/usr/bin/env python3
"""
build_papers_json.py — Aggregate the daily paper-scan markdown reports into a
single JSON file consumed by the Seymour website's "Daily Paper Summaries" tab.

Reads:  ~/.openclaw/workspace/outputs/paper-scan-YYYY-MM-DD.md
Writes: <repo>/data/papers.json   (override via PAPERS_JSON_OUT / PAPER_SCAN_DIR)

Schema:
{ "generated": "<ISO8601 UTC>",
  "days": [ { "date":"YYYY-MM-DD", "papersFrom":"<label>", "total":<int>,
              "papers":[ {"title","authors","source","tags":[],"summary","url"} ] } ] }

The markdown is machine-generated by daily-paper-scan.py (format_report), so the
layout per paper is fixed:
    N. *Title*
       Authors
       _cat_ 🧬 gene 🤖 ai        (optional tag line)
       Truncated summary…
       <url|📄 Paper>
"""
import os, re, json, glob
from datetime import datetime, timezone

HOME = os.path.expanduser("~")
SCAN_DIR = os.environ.get("PAPER_SCAN_DIR", os.path.join(HOME, ".openclaw/workspace/outputs"))
OUT = os.environ.get("PAPERS_JSON_OUT", os.path.join(HOME, "seymour-project/data/papers.json"))

FNAME_RE   = re.compile(r"paper-scan-(\d{4}-\d{2}-\d{2})\.md$")
TITLE_RE   = re.compile(r"Paper Scan\s*[—–-]\s*(.+?)\*")
TOTAL_RE   = re.compile(r"Total new papers:\s*(\d+)")
SECTION_RE = re.compile(r"^\*(arXiv|bioRxiv)\b")
ITEM_RE    = re.compile(r"^\d+\.\s+\*(.+?)\*\s*$")
URL_RE     = re.compile(r"^<(\S+?)\|")
TAGLINE_RE = re.compile(r"^_|🧬|🤖")


def parse_tags(line):
    tags = []
    m = re.match(r"^_(.+?)_", line)
    if m:
        tags += [t.strip() for t in m.group(1).split("|")]
    m = re.search(r"🧬\s*([^🤖]+)", line)
    if m:
        tags += [t.strip() for t in m.group(1).split(",")]
    m = re.search(r"🤖\s*(.+)$", line)
    if m:
        tags += [t.strip() for t in m.group(1).split(",")]
    seen, out = set(), []
    for t in tags:
        if t and t not in seen:
            seen.add(t)
            out.append(t)
    return out


def parse_report(path):
    date = FNAME_RE.search(os.path.basename(path)).group(1)
    papers_from, total, source = None, 0, None
    papers, cur, field = [], None, None

    def flush():
        nonlocal cur, field
        if cur is not None:
            papers.append(cur)
            cur, field = None, None

    with open(path, encoding="utf-8") as f:
        raw_lines = f.readlines()

    for raw in raw_lines:
        s = raw.strip()
        if not s:
            continue
        if papers_from is None:
            m = TITLE_RE.search(s)
            if m:
                papers_from = m.group(1).strip()
                continue
        if not papers:
            m = TOTAL_RE.search(s)
            if m:
                total = int(m.group(1))
                continue
        m = SECTION_RE.match(s)
        if m:
            flush()
            source = m.group(1)
            continue
        m = ITEM_RE.match(s)
        if m:
            flush()
            cur = {"title": m.group(1).strip(), "authors": "", "source": source,
                   "tags": [], "summary": "", "url": ""}
            field = "authors"
            continue
        # indented continuation lines belong to the current paper
        if cur is not None and (raw.startswith("   ") or raw.startswith("\t")):
            mu = URL_RE.match(s)
            if mu:
                cur["url"] = mu.group(1)
                flush()
                continue
            if field == "authors":
                cur["authors"] = s
                field = "after_authors"
                continue
            if field == "after_authors":
                if TAGLINE_RE.match(s):
                    cur["tags"] = parse_tags(s)
                    field = "summary"
                else:
                    cur["summary"] = s
                    field = "done"
                continue
            if field == "summary":
                cur["summary"] = s
                field = "done"
                continue
    flush()
    return {"date": date, "papersFrom": papers_from, "total": total, "papers": papers}


def main():
    files = sorted(glob.glob(os.path.join(SCAN_DIR, "paper-scan-*.md")))
    days = []
    for path in files:
        if not FNAME_RE.search(os.path.basename(path)):
            continue
        try:
            days.append(parse_report(path))
        except Exception as e:  # one bad file shouldn't sink the whole build
            print(f"WARN: failed to parse {path}: {e}")
    days.sort(key=lambda d: d["date"], reverse=True)
    out = {
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "days": days,
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
    n_papers = sum(len(d["papers"]) for d in days)
    print(f"Wrote {OUT}: {len(days)} days, {n_papers} papers")


if __name__ == "__main__":
    main()
